[build]
    command = "npm run build"
    publish = "dist"
    functions = "src/functions"
    NODE_ENV = "10.14.1"

[[redirects]]
    from = "/new"
    to = "/.netlify/functions/newRiddle"
    status = 200

[[redirects]]
    from = "/riddle/*"
    to = "/.netlify/functions/showRiddle?id=:splat"
    status = 302